config/routes.rb
Rails.application.routes.draw do
  root to: 'users#new'
  get 'signup', to: 'users#new', as: 'signup'
  get 'users/create'
  resources :users, only: [:show, :create, :new]
  get    'login',  to: 'sessions#new',     as: 'login'
  post   'login',  to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: 'logout'
  resources :orders, only: [:new, :create, :show]
  resources :cart_items, only: [:show, :create, :update, :destroy]
  resource :cart, only: [:show]
  resources :products, only: [:index, :show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  # 関連付け
  belongs_to :user, optional: true
  has_many :cart_items, dependent: :destroy
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  # 関連付け
  belongs_to :cart
  belongs_to :product

  # バリデーション
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
end

app/models/order.rb
class Order < ApplicationRecord
  # 関連付け
  belongs_to :user
  has_many :order_items, dependent: :destroy

  # バリデーション
  validates :status, presence: true
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  # 関連付け
  belongs_to :user
  has_many :order_items, dependent: :destroy

  # バリデーション
  validates :status, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
    # 関連付け
    has_many :cart_items
    has_many :order_items
  
    # バリデーション
    validates :name, presence: true
    validates :description, presence: true
    validates :price, presence: true, numericality: { greater_than: 0 }
    validates :stock, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  end
  

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  # 関連付け
  has_many :carts
  has_many :orders
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  
  def show
    @cart_items = current_cart.cart_items
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  # before_action :authenticate_user!
  before_action :authenticate_user
  def new
    @order = Order.new
    @cart_items = current_cart.cart_items
    # binding.pry
  end

  def create
    @order = Order.new(order_params)
    @order.user = current_user
    @order.total_price = calculate_total(@cart_items)

    if @order.save
      session.delete(:cart_id) # カートをクリア
      redirect_to @order, notice: '注文が完了しました。'
    else
      render :new
    end
  end

  # その他のアクション...

  private

  def order_params
    params.require(:order).permit(:address, :payment_method) # 必要に応じて調整
  end

  def calculate_total(cart_items)
    cart_items.inject(0) { |sum, item| sum + item.total_price }
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    binding.pry
    if user && user.authenticate(params[:session][:password])
      # ログイン成功
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      # ログイン失敗
      binding.pry
      flash.now[:danger] = 'メールアドレスまたはパスワードが間違っています'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end


  def create
    @user = User.new(user_params)
    if @user.save
      # 保存に成功した場合、ログインさせるなどの処理をここに記述
      session[:user_id] = @user.id
      binding.pry
      redirect_to user_path(@user), notice: 'ユーザー登録が完了しました。'
    else
      # 保存に失敗した場合、新規登録フォームを再表示
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyApp</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<%= javascript_importmap_tags %>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <%= link_to 'ec', root_path, class: 'navbar-brand' %>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to '商品一覧', products_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'カート', cart_path(session[:cart_id]), class: 'nav-link' %>
          </li>
          <!-- ログインしているかどうかで条件分岐 -->
          <% if current_user %>
            <li class="nav-item">
              <%= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link' %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'ログイン', login_path, class: 'nav-link' %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

  <%= yield %>
</body>
</html>